# Generated by Django 5.0.1 on 2024-02-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_form',
            old_name='dob',
            new_name='date_of_birth',
        ),
        migrations.AlterField(
            model_name='user_form',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user_form',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
