# Generated by Django 5.0.1 on 2024-02-11 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_dob_user_form_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_form',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
