# Generated by Django 5.0.1 on 2024-02-11 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_phone_user_form_phone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Form',
            new_name='UserRegistration',
        ),
    ]
